### PR TITLE
Cache dict construction and offer way to build individual emoji.

### PR DESCRIPTION
**Pull request by aquach**
Caching the dict is about a 4x speed increase, from my very coarse benchmarking. It has a notable impact on mobile too.

### CODE REVIEW

**Comment by banyan** [comment]
@aquach 

Thanks for the patch! I've just modified your PR a little bit here: https://github.com/banyan/react-emoji/pull/9

* Pass tests
* Change not to offer as public method, but as option (`isSingleEmoji`).
* Not raise an error if there is no emoji, that's safer just in case.

What do you have in your mind?

**Comment by aquach** [comment]
Thanks! Looks good, though I think I prefer raising an error if no emoji exists. Since the user is expecting an emoji out in the case of asking for a single emoji, it seems like unexpected behavior to silently return a string like `:chicken:` rather than the expected emoji. In fact, I have some code in my use of `react-emoji` that checks `typeof result === 'string'` and throws so that I know the emoji doesn't exist.

**Comment by banyan** [comment]
Thanks for the feedback! Yes, it makes sense. 

>Since the user is expecting an emoji out in the case of asking for a single emoji

The user will be either case like developer or end user. It's useful to throw while in middle of development. But how about production. If you typo `:smile:` as `:smlile:` and application will stop. Or maybe we can add strict option?

**Comment by aquach** [comment]
That's a great point. I like the idea of a strict check.

**Comment by banyan** [comment]
Thanks! I updated https://github.com/banyan/react-emoji/pull/9, could you have a look it again?

**Pull request merged**
